//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by VS
// </autogenerated>
//------------------------------------------------------------------------------
namespace RegularExpressionScratchpad
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            this.label3 = new System.Windows.Forms.Label();
            this.toolStrip1 = new System.Windows.Forms.ToolStrip();
            this.toolStripButtonInsert = new System.Windows.Forms.ToolStripDropDownButton();
            this.anchorsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.beginningOfStringToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.beginningOfMultilineAToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.endOfStringToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.endOfMultilineZToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.wordBoundrybToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.nonwordBoundryBToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.conditionalsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.expressionexpyesnoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.namedToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.characterClassesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.groupcharsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.negatedGroupcharsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem1 = new System.Windows.Forms.ToolStripSeparator();
            this.anyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.wordazAZ09wToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.nonwordWToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.whitespacefnrvsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.nonwhitespaceSToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.decimalDigitdToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.nondecimalDigitDToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.characterShortcutsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aSCIIValuexnnToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.bellaToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.carriageReturnrToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.cTRLCharCletterToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.escToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.formFeedfToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.newlinnToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.tabtToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.unicodeCharuxxxToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.verticalTabZvToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.groupingToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.captureexpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.namedCapturenamexToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.noncpatureToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.alternationxyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ignoreCaseiToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ignoreCaseOffiToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ignoreWhitespacexToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.ignoreWhitespaceOffxToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.explicitCapturenToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.explicitCaptureOffnToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.multilinemToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.multilineOffmToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.singlelinesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.singlelineOffsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.quantifiersToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.atLeastNnToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exactlyNnToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.oneOrMoreToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.fromNToMnmToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.zeroOrMoreToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.zeroOrOneToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem2 = new System.Windows.Forms.ToolStripSeparator();
            this.atLeastNNongreedynToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.exacltyNNongreedynToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.oneOrMoreNonGreedyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.fromNToMNonGreedynmToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.zeroOrMoreNonGreedyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.zeroOrOneNonGreedyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.zerowidthToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.negativeLookaheadxToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.negativeLookbehindxToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.positiveLookaheadxToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.positiveLookbehindToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripMatch = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonReplace = new System.Windows.Forms.ToolStripButton();
            this.toolStripButtonReplaceInFiles = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripButtonLibrary = new System.Windows.Forms.ToolStripButton();
            this.toolStripButton2 = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator4 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripButton1 = new System.Windows.Forms.ToolStripButton();
            this.toolStripSeparator3 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripDropDownButton1 = new System.Windows.Forms.ToolStripButton();
            this.textBoxInput = new System.Windows.Forms.RichTextBox();
            this.textBoxInterpretation = new System.Windows.Forms.RichTextBox();
            this.textBoxReplacement = new System.Windows.Forms.RichTextBox();
            this.treeView1 = new System.Windows.Forms.TreeView();
            this.labelLibrary = new System.Windows.Forms.Label();
            this.textBoxRegex = new System.Windows.Forms.RichTextBox();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.label4 = new System.Windows.Forms.Label();
            this.folderBrowserDialog1 = new System.Windows.Forms.FolderBrowserDialog();
            this.checkedListBoxOptions = new System.Windows.Forms.CheckedListBox();
            this.checkBoxTreatAsSingleString = new System.Windows.Forms.CheckBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.toolStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(7, 318);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(188, 26);
            this.label3.TabIndex = 5;
            this.label3.Text = "Replacement Text";
            // 
            // toolStrip1
            // 
            this.toolStrip1.AutoSize = false;
            this.toolStrip1.GripStyle = System.Windows.Forms.ToolStripGripStyle.Hidden;
            this.toolStrip1.ImageScalingSize = new System.Drawing.Size(32, 32);
            this.toolStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripButtonInsert,
            this.toolStripSeparator1,
            this.toolStripMatch,
            this.toolStripButtonReplace,
            this.toolStripButtonReplaceInFiles,
            this.toolStripSeparator2,
            this.toolStripButtonLibrary,
            this.toolStripButton2,
            this.toolStripSeparator4,
            this.toolStripButton1,
            this.toolStripSeparator3,
            this.toolStripDropDownButton1});
            this.toolStrip1.Location = new System.Drawing.Point(0, 0);
            this.toolStrip1.Name = "toolStrip1";
            this.toolStrip1.RenderMode = System.Windows.Forms.ToolStripRenderMode.Professional;
            this.toolStrip1.Size = new System.Drawing.Size(1188, 64);
            this.toolStrip1.Stretch = true;
            this.toolStrip1.TabIndex = 11;
            this.toolStrip1.Text = "toolStrip1";
            // 
            // toolStripButtonInsert
            // 
            this.toolStripButtonInsert.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Text;
            this.toolStripButtonInsert.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.anchorsToolStripMenuItem,
            this.conditionalsToolStripMenuItem,
            this.characterClassesToolStripMenuItem,
            this.characterShortcutsToolStripMenuItem,
            this.groupingToolStripMenuItem,
            this.optionsToolStripMenuItem,
            this.quantifiersToolStripMenuItem,
            this.zerowidthToolStripMenuItem});
            this.toolStripButtonInsert.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButtonInsert.Image")));
            this.toolStripButtonInsert.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripButtonInsert.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonInsert.Name = "toolStripButtonInsert";
            this.toolStripButtonInsert.Size = new System.Drawing.Size(96, 61);
            this.toolStripButtonInsert.Text = "Insert";
            // 
            // anchorsToolStripMenuItem
            // 
            this.anchorsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.beginningOfStringToolStripMenuItem,
            this.beginningOfMultilineAToolStripMenuItem,
            this.endOfStringToolStripMenuItem,
            this.endOfMultilineZToolStripMenuItem,
            this.wordBoundrybToolStripMenuItem,
            this.nonwordBoundryBToolStripMenuItem});
            this.anchorsToolStripMenuItem.Name = "anchorsToolStripMenuItem";
            this.anchorsToolStripMenuItem.Size = new System.Drawing.Size(319, 38);
            this.anchorsToolStripMenuItem.Text = "&Anchors";
            // 
            // beginningOfStringToolStripMenuItem
            // 
            this.beginningOfStringToolStripMenuItem.Name = "beginningOfStringToolStripMenuItem";
            this.beginningOfStringToolStripMenuItem.Size = new System.Drawing.Size(389, 38);
            this.beginningOfStringToolStripMenuItem.Text = "Beginning of string: ^";
            this.beginningOfStringToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // beginningOfMultilineAToolStripMenuItem
            // 
            this.beginningOfMultilineAToolStripMenuItem.Name = "beginningOfMultilineAToolStripMenuItem";
            this.beginningOfMultilineAToolStripMenuItem.Size = new System.Drawing.Size(389, 38);
            this.beginningOfMultilineAToolStripMenuItem.Text = "Beginning of multiline: \\A";
            this.beginningOfMultilineAToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // endOfStringToolStripMenuItem
            // 
            this.endOfStringToolStripMenuItem.Name = "endOfStringToolStripMenuItem";
            this.endOfStringToolStripMenuItem.Size = new System.Drawing.Size(389, 38);
            this.endOfStringToolStripMenuItem.Text = "End of string: $";
            this.endOfStringToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // endOfMultilineZToolStripMenuItem
            // 
            this.endOfMultilineZToolStripMenuItem.Name = "endOfMultilineZToolStripMenuItem";
            this.endOfMultilineZToolStripMenuItem.Size = new System.Drawing.Size(389, 38);
            this.endOfMultilineZToolStripMenuItem.Text = "End of multiline: \\Z";
            this.endOfMultilineZToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // wordBoundrybToolStripMenuItem
            // 
            this.wordBoundrybToolStripMenuItem.Name = "wordBoundrybToolStripMenuItem";
            this.wordBoundrybToolStripMenuItem.Size = new System.Drawing.Size(389, 38);
            this.wordBoundrybToolStripMenuItem.Text = "Word boundry: \\b";
            this.wordBoundrybToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // nonwordBoundryBToolStripMenuItem
            // 
            this.nonwordBoundryBToolStripMenuItem.Name = "nonwordBoundryBToolStripMenuItem";
            this.nonwordBoundryBToolStripMenuItem.Size = new System.Drawing.Size(389, 38);
            this.nonwordBoundryBToolStripMenuItem.Text = "Non-word boundry: \\B";
            this.nonwordBoundryBToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // conditionalsToolStripMenuItem
            // 
            this.conditionalsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.expressionexpyesnoToolStripMenuItem,
            this.namedToolStripMenuItem});
            this.conditionalsToolStripMenuItem.Name = "conditionalsToolStripMenuItem";
            this.conditionalsToolStripMenuItem.Size = new System.Drawing.Size(319, 38);
            this.conditionalsToolStripMenuItem.Text = "Conditionals";
            // 
            // expressionexpyesnoToolStripMenuItem
            // 
            this.expressionexpyesnoToolStripMenuItem.Name = "expressionexpyesnoToolStripMenuItem";
            this.expressionexpyesnoToolStripMenuItem.Size = new System.Drawing.Size(409, 38);
            this.expressionexpyesnoToolStripMenuItem.Text = "Expression: (?<exp>)yes|no)";
            this.expressionexpyesnoToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // namedToolStripMenuItem
            // 
            this.namedToolStripMenuItem.Name = "namedToolStripMenuItem";
            this.namedToolStripMenuItem.Size = new System.Drawing.Size(409, 38);
            this.namedToolStripMenuItem.Text = "Named: (?(<name>)yes|no)";
            this.namedToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // characterClassesToolStripMenuItem
            // 
            this.characterClassesToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.groupcharsToolStripMenuItem,
            this.negatedGroupcharsToolStripMenuItem,
            this.toolStripMenuItem1,
            this.anyToolStripMenuItem,
            this.wordazAZ09wToolStripMenuItem,
            this.nonwordWToolStripMenuItem,
            this.whitespacefnrvsToolStripMenuItem,
            this.nonwhitespaceSToolStripMenuItem,
            this.decimalDigitdToolStripMenuItem,
            this.nondecimalDigitDToolStripMenuItem});
            this.characterClassesToolStripMenuItem.Name = "characterClassesToolStripMenuItem";
            this.characterClassesToolStripMenuItem.Size = new System.Drawing.Size(319, 38);
            this.characterClassesToolStripMenuItem.Text = "Character classes";
            // 
            // groupcharsToolStripMenuItem
            // 
            this.groupcharsToolStripMenuItem.Name = "groupcharsToolStripMenuItem";
            this.groupcharsToolStripMenuItem.Size = new System.Drawing.Size(406, 38);
            this.groupcharsToolStripMenuItem.Text = "Group: [<chars>]";
            this.groupcharsToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // negatedGroupcharsToolStripMenuItem
            // 
            this.negatedGroupcharsToolStripMenuItem.Name = "negatedGroupcharsToolStripMenuItem";
            this.negatedGroupcharsToolStripMenuItem.Size = new System.Drawing.Size(406, 38);
            this.negatedGroupcharsToolStripMenuItem.Text = "Negated group: [^<chars>]";
            this.negatedGroupcharsToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // toolStripMenuItem1
            // 
            this.toolStripMenuItem1.Name = "toolStripMenuItem1";
            this.toolStripMenuItem1.Size = new System.Drawing.Size(403, 6);
            // 
            // anyToolStripMenuItem
            // 
            this.anyToolStripMenuItem.Name = "anyToolStripMenuItem";
            this.anyToolStripMenuItem.Size = new System.Drawing.Size(406, 38);
            this.anyToolStripMenuItem.Text = "Any: .";
            this.anyToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // wordazAZ09wToolStripMenuItem
            // 
            this.wordazAZ09wToolStripMenuItem.Name = "wordazAZ09wToolStripMenuItem";
            this.wordazAZ09wToolStripMenuItem.Size = new System.Drawing.Size(406, 38);
            this.wordazAZ09wToolStripMenuItem.Text = "Word [a-zA-Z0-9]: \\w";
            this.wordazAZ09wToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // nonwordWToolStripMenuItem
            // 
            this.nonwordWToolStripMenuItem.Name = "nonwordWToolStripMenuItem";
            this.nonwordWToolStripMenuItem.Size = new System.Drawing.Size(406, 38);
            this.nonwordWToolStripMenuItem.Text = "Non-word: \\W";
            this.nonwordWToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // whitespacefnrvsToolStripMenuItem
            // 
            this.whitespacefnrvsToolStripMenuItem.Name = "whitespacefnrvsToolStripMenuItem";
            this.whitespacefnrvsToolStripMenuItem.Size = new System.Drawing.Size(406, 38);
            this.whitespacefnrvsToolStripMenuItem.Text = "Whitespace [\\f\\n\\r\\v]: \\s";
            this.whitespacefnrvsToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // nonwhitespaceSToolStripMenuItem
            // 
            this.nonwhitespaceSToolStripMenuItem.Name = "nonwhitespaceSToolStripMenuItem";
            this.nonwhitespaceSToolStripMenuItem.Size = new System.Drawing.Size(406, 38);
            this.nonwhitespaceSToolStripMenuItem.Text = "Non-whitespace: \\S";
            this.nonwhitespaceSToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // decimalDigitdToolStripMenuItem
            // 
            this.decimalDigitdToolStripMenuItem.Name = "decimalDigitdToolStripMenuItem";
            this.decimalDigitdToolStripMenuItem.Size = new System.Drawing.Size(406, 38);
            this.decimalDigitdToolStripMenuItem.Text = "Decimal digit: \\d";
            this.decimalDigitdToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // nondecimalDigitDToolStripMenuItem
            // 
            this.nondecimalDigitDToolStripMenuItem.Name = "nondecimalDigitDToolStripMenuItem";
            this.nondecimalDigitDToolStripMenuItem.Size = new System.Drawing.Size(406, 38);
            this.nondecimalDigitDToolStripMenuItem.Text = "Non-decimal digit: \\D";
            this.nondecimalDigitDToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // characterShortcutsToolStripMenuItem
            // 
            this.characterShortcutsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.aSCIIValuexnnToolStripMenuItem,
            this.bellaToolStripMenuItem,
            this.carriageReturnrToolStripMenuItem,
            this.cTRLCharCletterToolStripMenuItem,
            this.escToolStripMenuItem,
            this.formFeedfToolStripMenuItem,
            this.newlinnToolStripMenuItem,
            this.tabtToolStripMenuItem,
            this.unicodeCharuxxxToolStripMenuItem,
            this.verticalTabZvToolStripMenuItem});
            this.characterShortcutsToolStripMenuItem.Name = "characterShortcutsToolStripMenuItem";
            this.characterShortcutsToolStripMenuItem.Size = new System.Drawing.Size(319, 38);
            this.characterShortcutsToolStripMenuItem.Text = "Character shortcuts";
            // 
            // aSCIIValuexnnToolStripMenuItem
            // 
            this.aSCIIValuexnnToolStripMenuItem.Name = "aSCIIValuexnnToolStripMenuItem";
            this.aSCIIValuexnnToolStripMenuItem.Size = new System.Drawing.Size(354, 38);
            this.aSCIIValuexnnToolStripMenuItem.Text = "ASCII value: \\x<nn>";
            this.aSCIIValuexnnToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // bellaToolStripMenuItem
            // 
            this.bellaToolStripMenuItem.Name = "bellaToolStripMenuItem";
            this.bellaToolStripMenuItem.Size = new System.Drawing.Size(354, 38);
            this.bellaToolStripMenuItem.Text = "Bell: \\a";
            this.bellaToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // carriageReturnrToolStripMenuItem
            // 
            this.carriageReturnrToolStripMenuItem.Name = "carriageReturnrToolStripMenuItem";
            this.carriageReturnrToolStripMenuItem.Size = new System.Drawing.Size(354, 38);
            this.carriageReturnrToolStripMenuItem.Text = "Carriage return: \\r";
            this.carriageReturnrToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // cTRLCharCletterToolStripMenuItem
            // 
            this.cTRLCharCletterToolStripMenuItem.Name = "cTRLCharCletterToolStripMenuItem";
            this.cTRLCharCletterToolStripMenuItem.Size = new System.Drawing.Size(354, 38);
            this.cTRLCharCletterToolStripMenuItem.Text = "CTRL char: \\C<letter>";
            this.cTRLCharCletterToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // escToolStripMenuItem
            // 
            this.escToolStripMenuItem.Name = "escToolStripMenuItem";
            this.escToolStripMenuItem.Size = new System.Drawing.Size(354, 38);
            this.escToolStripMenuItem.Text = "Escape: \\e";
            this.escToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // formFeedfToolStripMenuItem
            // 
            this.formFeedfToolStripMenuItem.Name = "formFeedfToolStripMenuItem";
            this.formFeedfToolStripMenuItem.Size = new System.Drawing.Size(354, 38);
            this.formFeedfToolStripMenuItem.Text = "Form feed: \\f";
            this.formFeedfToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // newlinnToolStripMenuItem
            // 
            this.newlinnToolStripMenuItem.Name = "newlinnToolStripMenuItem";
            this.newlinnToolStripMenuItem.Size = new System.Drawing.Size(354, 38);
            this.newlinnToolStripMenuItem.Text = "Newline: \\n";
            this.newlinnToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // tabtToolStripMenuItem
            // 
            this.tabtToolStripMenuItem.Name = "tabtToolStripMenuItem";
            this.tabtToolStripMenuItem.Size = new System.Drawing.Size(354, 38);
            this.tabtToolStripMenuItem.Text = "Tab: \\t";
            this.tabtToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // unicodeCharuxxxToolStripMenuItem
            // 
            this.unicodeCharuxxxToolStripMenuItem.Name = "unicodeCharuxxxToolStripMenuItem";
            this.unicodeCharuxxxToolStripMenuItem.Size = new System.Drawing.Size(354, 38);
            this.unicodeCharuxxxToolStripMenuItem.Text = "Unicode char: \\u<xxx>";
            this.unicodeCharuxxxToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // verticalTabZvToolStripMenuItem
            // 
            this.verticalTabZvToolStripMenuItem.Name = "verticalTabZvToolStripMenuItem";
            this.verticalTabZvToolStripMenuItem.Size = new System.Drawing.Size(354, 38);
            this.verticalTabZvToolStripMenuItem.Text = "Vertical tab: \\v";
            this.verticalTabZvToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // groupingToolStripMenuItem
            // 
            this.groupingToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.captureexpToolStripMenuItem,
            this.namedCapturenamexToolStripMenuItem,
            this.noncpatureToolStripMenuItem,
            this.alternationxyToolStripMenuItem});
            this.groupingToolStripMenuItem.Name = "groupingToolStripMenuItem";
            this.groupingToolStripMenuItem.Size = new System.Drawing.Size(319, 38);
            this.groupingToolStripMenuItem.Text = "Grouping";
            // 
            // captureexpToolStripMenuItem
            // 
            this.captureexpToolStripMenuItem.Name = "captureexpToolStripMenuItem";
            this.captureexpToolStripMenuItem.Size = new System.Drawing.Size(451, 38);
            this.captureexpToolStripMenuItem.Text = "Capture: (<exp>)";
            this.captureexpToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // namedCapturenamexToolStripMenuItem
            // 
            this.namedCapturenamexToolStripMenuItem.Name = "namedCapturenamexToolStripMenuItem";
            this.namedCapturenamexToolStripMenuItem.Size = new System.Drawing.Size(451, 38);
            this.namedCapturenamexToolStripMenuItem.Text = "Named capture: (?<<name>>x)";
            this.namedCapturenamexToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // noncpatureToolStripMenuItem
            // 
            this.noncpatureToolStripMenuItem.Name = "noncpatureToolStripMenuItem";
            this.noncpatureToolStripMenuItem.Size = new System.Drawing.Size(451, 38);
            this.noncpatureToolStripMenuItem.Text = "Non-capture: (?:<exp>)";
            this.noncpatureToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // alternationxyToolStripMenuItem
            // 
            this.alternationxyToolStripMenuItem.Name = "alternationxyToolStripMenuItem";
            this.alternationxyToolStripMenuItem.Size = new System.Drawing.Size(451, 38);
            this.alternationxyToolStripMenuItem.Text = "Alternation: (<x>|<y>)";
            this.alternationxyToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // optionsToolStripMenuItem
            // 
            this.optionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.ignoreCaseiToolStripMenuItem,
            this.ignoreCaseOffiToolStripMenuItem,
            this.ignoreWhitespacexToolStripMenuItem,
            this.ignoreWhitespaceOffxToolStripMenuItem,
            this.explicitCapturenToolStripMenuItem,
            this.explicitCaptureOffnToolStripMenuItem,
            this.multilinemToolStripMenuItem,
            this.multilineOffmToolStripMenuItem,
            this.singlelinesToolStripMenuItem,
            this.singlelineOffsToolStripMenuItem});
            this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
            this.optionsToolStripMenuItem.Size = new System.Drawing.Size(319, 38);
            this.optionsToolStripMenuItem.Text = "Options";
            // 
            // ignoreCaseiToolStripMenuItem
            // 
            this.ignoreCaseiToolStripMenuItem.Name = "ignoreCaseiToolStripMenuItem";
            this.ignoreCaseiToolStripMenuItem.Size = new System.Drawing.Size(408, 38);
            this.ignoreCaseiToolStripMenuItem.Text = "Ignore case: (?i:)";
            this.ignoreCaseiToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // ignoreCaseOffiToolStripMenuItem
            // 
            this.ignoreCaseOffiToolStripMenuItem.Name = "ignoreCaseOffiToolStripMenuItem";
            this.ignoreCaseOffiToolStripMenuItem.Size = new System.Drawing.Size(408, 38);
            this.ignoreCaseOffiToolStripMenuItem.Text = "Ignore case off: (?-i:)";
            this.ignoreCaseOffiToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // ignoreWhitespacexToolStripMenuItem
            // 
            this.ignoreWhitespacexToolStripMenuItem.Name = "ignoreWhitespacexToolStripMenuItem";
            this.ignoreWhitespacexToolStripMenuItem.Size = new System.Drawing.Size(408, 38);
            this.ignoreWhitespacexToolStripMenuItem.Text = "Ignore whitespace: (?x:)";
            this.ignoreWhitespacexToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // ignoreWhitespaceOffxToolStripMenuItem
            // 
            this.ignoreWhitespaceOffxToolStripMenuItem.Name = "ignoreWhitespaceOffxToolStripMenuItem";
            this.ignoreWhitespaceOffxToolStripMenuItem.Size = new System.Drawing.Size(408, 38);
            this.ignoreWhitespaceOffxToolStripMenuItem.Text = "Ignore whitespace off: (?-x:)";
            this.ignoreWhitespaceOffxToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // explicitCapturenToolStripMenuItem
            // 
            this.explicitCapturenToolStripMenuItem.Name = "explicitCapturenToolStripMenuItem";
            this.explicitCapturenToolStripMenuItem.Size = new System.Drawing.Size(408, 38);
            this.explicitCapturenToolStripMenuItem.Text = "Explicit capture: (?n:)";
            this.explicitCapturenToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // explicitCaptureOffnToolStripMenuItem
            // 
            this.explicitCaptureOffnToolStripMenuItem.Name = "explicitCaptureOffnToolStripMenuItem";
            this.explicitCaptureOffnToolStripMenuItem.Size = new System.Drawing.Size(408, 38);
            this.explicitCaptureOffnToolStripMenuItem.Text = "Explicit capture off: (?-n:)";
            this.explicitCaptureOffnToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // multilinemToolStripMenuItem
            // 
            this.multilinemToolStripMenuItem.Name = "multilinemToolStripMenuItem";
            this.multilinemToolStripMenuItem.Size = new System.Drawing.Size(408, 38);
            this.multilinemToolStripMenuItem.Text = "Multiline: (?m:)";
            this.multilinemToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // multilineOffmToolStripMenuItem
            // 
            this.multilineOffmToolStripMenuItem.Name = "multilineOffmToolStripMenuItem";
            this.multilineOffmToolStripMenuItem.Size = new System.Drawing.Size(408, 38);
            this.multilineOffmToolStripMenuItem.Text = "Multiline off: (?-m:)";
            this.multilineOffmToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // singlelinesToolStripMenuItem
            // 
            this.singlelinesToolStripMenuItem.Name = "singlelinesToolStripMenuItem";
            this.singlelinesToolStripMenuItem.Size = new System.Drawing.Size(408, 38);
            this.singlelinesToolStripMenuItem.Text = "Singleline: (?s:)";
            this.singlelinesToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // singlelineOffsToolStripMenuItem
            // 
            this.singlelineOffsToolStripMenuItem.Name = "singlelineOffsToolStripMenuItem";
            this.singlelineOffsToolStripMenuItem.Size = new System.Drawing.Size(408, 38);
            this.singlelineOffsToolStripMenuItem.Text = "Singleline off: (?-s:)";
            this.singlelineOffsToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // quantifiersToolStripMenuItem
            // 
            this.quantifiersToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.atLeastNnToolStripMenuItem,
            this.exactlyNnToolStripMenuItem,
            this.oneOrMoreToolStripMenuItem,
            this.fromNToMnmToolStripMenuItem,
            this.zeroOrMoreToolStripMenuItem,
            this.zeroOrOneToolStripMenuItem,
            this.toolStripMenuItem2,
            this.atLeastNNongreedynToolStripMenuItem,
            this.exacltyNNongreedynToolStripMenuItem,
            this.oneOrMoreNonGreedyToolStripMenuItem,
            this.fromNToMNonGreedynmToolStripMenuItem,
            this.zeroOrMoreNonGreedyToolStripMenuItem,
            this.zeroOrOneNonGreedyToolStripMenuItem});
            this.quantifiersToolStripMenuItem.Name = "quantifiersToolStripMenuItem";
            this.quantifiersToolStripMenuItem.Size = new System.Drawing.Size(319, 38);
            this.quantifiersToolStripMenuItem.Text = "Quantifiers";
            // 
            // atLeastNnToolStripMenuItem
            // 
            this.atLeastNnToolStripMenuItem.Name = "atLeastNnToolStripMenuItem";
            this.atLeastNnToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.atLeastNnToolStripMenuItem.Text = "At least n: {<n>,}";
            this.atLeastNnToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // exactlyNnToolStripMenuItem
            // 
            this.exactlyNnToolStripMenuItem.Name = "exactlyNnToolStripMenuItem";
            this.exactlyNnToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.exactlyNnToolStripMenuItem.Text = "Exactly n: {<n>}";
            this.exactlyNnToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // oneOrMoreToolStripMenuItem
            // 
            this.oneOrMoreToolStripMenuItem.Name = "oneOrMoreToolStripMenuItem";
            this.oneOrMoreToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.oneOrMoreToolStripMenuItem.Text = "One or more: +";
            this.oneOrMoreToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // fromNToMnmToolStripMenuItem
            // 
            this.fromNToMnmToolStripMenuItem.Name = "fromNToMnmToolStripMenuItem";
            this.fromNToMnmToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.fromNToMnmToolStripMenuItem.Text = "From n to m: {<n>, <m>}";
            this.fromNToMnmToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // zeroOrMoreToolStripMenuItem
            // 
            this.zeroOrMoreToolStripMenuItem.Name = "zeroOrMoreToolStripMenuItem";
            this.zeroOrMoreToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.zeroOrMoreToolStripMenuItem.Text = "Zero or more: *";
            this.zeroOrMoreToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // zeroOrOneToolStripMenuItem
            // 
            this.zeroOrOneToolStripMenuItem.Name = "zeroOrOneToolStripMenuItem";
            this.zeroOrOneToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.zeroOrOneToolStripMenuItem.Text = "Zero or one: ?";
            this.zeroOrOneToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // toolStripMenuItem2
            // 
            this.toolStripMenuItem2.Name = "toolStripMenuItem2";
            this.toolStripMenuItem2.Size = new System.Drawing.Size(522, 6);
            // 
            // atLeastNNongreedynToolStripMenuItem
            // 
            this.atLeastNNongreedynToolStripMenuItem.Name = "atLeastNNongreedynToolStripMenuItem";
            this.atLeastNNongreedynToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.atLeastNNongreedynToolStripMenuItem.Text = "At least n non-greedy: {<n>}?";
            this.atLeastNNongreedynToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // exacltyNNongreedynToolStripMenuItem
            // 
            this.exacltyNNongreedynToolStripMenuItem.Name = "exacltyNNongreedynToolStripMenuItem";
            this.exacltyNNongreedynToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.exacltyNNongreedynToolStripMenuItem.Text = "Exactly n non-greedy: {<n>}?";
            this.exacltyNNongreedynToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // oneOrMoreNonGreedyToolStripMenuItem
            // 
            this.oneOrMoreNonGreedyToolStripMenuItem.Name = "oneOrMoreNonGreedyToolStripMenuItem";
            this.oneOrMoreNonGreedyToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.oneOrMoreNonGreedyToolStripMenuItem.Text = "One or more non greedy: +?";
            this.oneOrMoreNonGreedyToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // fromNToMNonGreedynmToolStripMenuItem
            // 
            this.fromNToMNonGreedynmToolStripMenuItem.Name = "fromNToMNonGreedynmToolStripMenuItem";
            this.fromNToMNonGreedynmToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.fromNToMNonGreedynmToolStripMenuItem.Text = "From n to m non greedy: {<n>, <m>}?";
            this.fromNToMNonGreedynmToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // zeroOrMoreNonGreedyToolStripMenuItem
            // 
            this.zeroOrMoreNonGreedyToolStripMenuItem.Name = "zeroOrMoreNonGreedyToolStripMenuItem";
            this.zeroOrMoreNonGreedyToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.zeroOrMoreNonGreedyToolStripMenuItem.Text = "Zero or more non greedy: *?";
            this.zeroOrMoreNonGreedyToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // zeroOrOneNonGreedyToolStripMenuItem
            // 
            this.zeroOrOneNonGreedyToolStripMenuItem.Name = "zeroOrOneNonGreedyToolStripMenuItem";
            this.zeroOrOneNonGreedyToolStripMenuItem.Size = new System.Drawing.Size(525, 38);
            this.zeroOrOneNonGreedyToolStripMenuItem.Text = "Zero or one non greedy: ??";
            this.zeroOrOneNonGreedyToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // zerowidthToolStripMenuItem
            // 
            this.zerowidthToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.negativeLookaheadxToolStripMenuItem,
            this.negativeLookbehindxToolStripMenuItem,
            this.positiveLookaheadxToolStripMenuItem,
            this.positiveLookbehindToolStripMenuItem});
            this.zerowidthToolStripMenuItem.Name = "zerowidthToolStripMenuItem";
            this.zerowidthToolStripMenuItem.Size = new System.Drawing.Size(319, 38);
            this.zerowidthToolStripMenuItem.Text = "Zero-width";
            // 
            // negativeLookaheadxToolStripMenuItem
            // 
            this.negativeLookaheadxToolStripMenuItem.Name = "negativeLookaheadxToolStripMenuItem";
            this.negativeLookaheadxToolStripMenuItem.Size = new System.Drawing.Size(441, 38);
            this.negativeLookaheadxToolStripMenuItem.Text = "Negative lookahead: (?!<x>)";
            this.negativeLookaheadxToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // negativeLookbehindxToolStripMenuItem
            // 
            this.negativeLookbehindxToolStripMenuItem.Name = "negativeLookbehindxToolStripMenuItem";
            this.negativeLookbehindxToolStripMenuItem.Size = new System.Drawing.Size(441, 38);
            this.negativeLookbehindxToolStripMenuItem.Text = "Negative lookbehind: (?<!<x>)";
            this.negativeLookbehindxToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // positiveLookaheadxToolStripMenuItem
            // 
            this.positiveLookaheadxToolStripMenuItem.Name = "positiveLookaheadxToolStripMenuItem";
            this.positiveLookaheadxToolStripMenuItem.Size = new System.Drawing.Size(441, 38);
            this.positiveLookaheadxToolStripMenuItem.Text = "Positive lookahead: (?=<x>)";
            this.positiveLookaheadxToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // positiveLookbehindToolStripMenuItem
            // 
            this.positiveLookbehindToolStripMenuItem.Name = "positiveLookbehindToolStripMenuItem";
            this.positiveLookbehindToolStripMenuItem.Size = new System.Drawing.Size(441, 38);
            this.positiveLookbehindToolStripMenuItem.Text = "Positive lookbehind: (?<=<x>)";
            this.positiveLookbehindToolStripMenuItem.Click += new System.EventHandler(this.InsertText);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(6, 32);
            // 
            // toolStripMatch
            // 
            this.toolStripMatch.Image = ((System.Drawing.Image)(resources.GetObject("toolStripMatch.Image")));
            this.toolStripMatch.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripMatch.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripMatch.Name = "toolStripMatch";
            this.toolStripMatch.Size = new System.Drawing.Size(110, 29);
            this.toolStripMatch.Text = "Match";
            this.toolStripMatch.Click += new System.EventHandler(this.toolStripMatch_Click);
            // 
            // toolStripButtonReplace
            // 
            this.toolStripButtonReplace.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButtonReplace.Image")));
            this.toolStripButtonReplace.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripButtonReplace.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonReplace.Name = "toolStripButtonReplace";
            this.toolStripButtonReplace.Size = new System.Drawing.Size(125, 29);
            this.toolStripButtonReplace.Text = "Replace";
            this.toolStripButtonReplace.ToolTipText = "Replace";
            this.toolStripButtonReplace.Click += new System.EventHandler(this.ToolStripButtonReplace_Click);
            // 
            // toolStripButtonReplaceInFiles
            // 
            this.toolStripButtonReplaceInFiles.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButtonReplaceInFiles.Image")));
            this.toolStripButtonReplaceInFiles.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripButtonReplaceInFiles.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonReplaceInFiles.Name = "toolStripButtonReplaceInFiles";
            this.toolStripButtonReplaceInFiles.Size = new System.Drawing.Size(206, 29);
            this.toolStripButtonReplaceInFiles.Text = "Replace In Files";
            this.toolStripButtonReplaceInFiles.Click += new System.EventHandler(this.toolStripButtonReplaceInFiles_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(6, 32);
            // 
            // toolStripButtonLibrary
            // 
            this.toolStripButtonLibrary.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButtonLibrary.Image")));
            this.toolStripButtonLibrary.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripButtonLibrary.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButtonLibrary.Name = "toolStripButtonLibrary";
            this.toolStripButtonLibrary.Size = new System.Drawing.Size(114, 29);
            this.toolStripButtonLibrary.Text = "Library";
            this.toolStripButtonLibrary.Click += new System.EventHandler(this.ToolStripButton3_Click);
            // 
            // toolStripButton2
            // 
            this.toolStripButton2.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButton2.Image")));
            this.toolStripButton2.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripButton2.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButton2.Name = "toolStripButton2";
            this.toolStripButton2.Size = new System.Drawing.Size(190, 29);
            this.toolStripButton2.Text = "Run Selection";
            this.toolStripButton2.Click += new System.EventHandler(this.ToolStripButton2_Click);
            // 
            // toolStripSeparator4
            // 
            this.toolStripSeparator4.Name = "toolStripSeparator4";
            this.toolStripSeparator4.Size = new System.Drawing.Size(6, 32);
            // 
            // toolStripButton1
            // 
            this.toolStripButton1.Image = ((System.Drawing.Image)(resources.GetObject("toolStripButton1.Image")));
            this.toolStripButton1.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripButton1.Name = "toolStripButton1";
            this.toolStripButton1.Size = new System.Drawing.Size(131, 29);
            this.toolStripButton1.Text = "&Matcher";
            this.toolStripButton1.Click += new System.EventHandler(this.toolStripButton1_Click);
            // 
            // toolStripSeparator3
            // 
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            this.toolStripSeparator3.Size = new System.Drawing.Size(6, 32);
            // 
            // toolStripDropDownButton1
            // 
            this.toolStripDropDownButton1.DisplayStyle = System.Windows.Forms.ToolStripItemDisplayStyle.Image;
            this.toolStripDropDownButton1.Image = ((System.Drawing.Image)(resources.GetObject("toolStripDropDownButton1.Image")));
            this.toolStripDropDownButton1.ImageScaling = System.Windows.Forms.ToolStripItemImageScaling.None;
            this.toolStripDropDownButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.toolStripDropDownButton1.Name = "toolStripDropDownButton1";
            this.toolStripDropDownButton1.Overflow = System.Windows.Forms.ToolStripItemOverflow.Never;
            this.toolStripDropDownButton1.Size = new System.Drawing.Size(28, 29);
            this.toolStripDropDownButton1.Text = "&Help";
            this.toolStripDropDownButton1.ToolTipText = "About";
            this.toolStripDropDownButton1.Click += new System.EventHandler(this.toolStripDropDownButton1_Click);
            // 
            // textBoxInput
            // 
            this.textBoxInput.AllowDrop = true;
            this.textBoxInput.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.textBoxInput.BackColor = System.Drawing.Color.White;
            this.textBoxInput.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.textBoxInput.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBoxInput.Location = new System.Drawing.Point(12, 526);
            this.textBoxInput.MaxLength = 500000;
            this.textBoxInput.Name = "textBoxInput";
            this.textBoxInput.Size = new System.Drawing.Size(698, 120);
            this.textBoxInput.TabIndex = 2;
            this.textBoxInput.Text = "";
            this.toolTip1.SetToolTip(this.textBoxInput, "Input Text / Result");
            this.textBoxInput.DragDrop += new System.Windows.Forms.DragEventHandler(this.TextBoxInput_dragdrop);
            this.textBoxInput.DragEnter += new System.Windows.Forms.DragEventHandler(this.TextBoxInput_DragEnter);
            // 
            // textBoxInterpretation
            // 
            this.textBoxInterpretation.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.textBoxInterpretation.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.textBoxInterpretation.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.textBoxInterpretation.Font = new System.Drawing.Font("Arial", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBoxInterpretation.Location = new System.Drawing.Point(731, 141);
            this.textBoxInterpretation.Name = "textBoxInterpretation";
            this.textBoxInterpretation.Size = new System.Drawing.Size(437, 332);
            this.textBoxInterpretation.TabIndex = 14;
            this.textBoxInterpretation.TabStop = false;
            this.textBoxInterpretation.Text = "";
            this.toolTip1.SetToolTip(this.textBoxInterpretation, "Interpretation");
            // 
            // textBoxReplacement
            // 
            this.textBoxReplacement.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.textBoxReplacement.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBoxReplacement.Location = new System.Drawing.Point(12, 347);
            this.textBoxReplacement.MaxLength = 500000;
            this.textBoxReplacement.Name = "textBoxReplacement";
            this.textBoxReplacement.Size = new System.Drawing.Size(698, 126);
            this.textBoxReplacement.TabIndex = 1;
            this.textBoxReplacement.Text = "";
            this.toolTip1.SetToolTip(this.textBoxReplacement, "Replacement Text");
            // 
            // treeView1
            // 
            this.treeView1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.treeView1.CheckBoxes = true;
            this.treeView1.Location = new System.Drawing.Point(731, 526);
            this.treeView1.Name = "treeView1";
            this.treeView1.Size = new System.Drawing.Size(437, 120);
            this.treeView1.TabIndex = 3;
            this.treeView1.AfterCheck += new System.Windows.Forms.TreeViewEventHandler(this.treeView1_AfterCheck);
            // 
            // labelLibrary
            // 
            this.labelLibrary.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.labelLibrary.AutoSize = true;
            this.labelLibrary.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelLibrary.Location = new System.Drawing.Point(726, 497);
            this.labelLibrary.Name = "labelLibrary";
            this.labelLibrary.Size = new System.Drawing.Size(130, 26);
            this.labelLibrary.TabIndex = 27;
            this.labelLibrary.Text = "Task Library";
            // 
            // textBoxRegex
            // 
            this.textBoxRegex.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.textBoxRegex.Font = new System.Drawing.Font("Arial", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textBoxRegex.Location = new System.Drawing.Point(12, 141);
            this.textBoxRegex.MaxLength = 500;
            this.textBoxRegex.Name = "textBoxRegex";
            this.textBoxRegex.Size = new System.Drawing.Size(698, 152);
            this.textBoxRegex.TabIndex = 0;
            this.textBoxRegex.Text = "";
            this.toolTip1.SetToolTip(this.textBoxRegex, "Regular Expression");
            this.textBoxRegex.TextChanged += new System.EventHandler(this.TextBoxRegex_TextChanged);
            this.textBoxRegex.KeyDown += new System.Windows.Forms.KeyEventHandler(this.textBoxRegex_KeyDown);
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(7, 497);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(152, 26);
            this.label4.TabIndex = 29;
            this.label4.Text = "Text to Search";
            this.toolTip1.SetToolTip(this.label4, "Text to Search");
            // 
            // checkedListBoxOptions
            // 
            this.checkedListBoxOptions.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.checkedListBoxOptions.BackColor = System.Drawing.SystemColors.Control;
            this.checkedListBoxOptions.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.checkedListBoxOptions.CheckOnClick = true;
            this.checkedListBoxOptions.Cursor = System.Windows.Forms.Cursors.Hand;
            this.checkedListBoxOptions.FormattingEnabled = true;
            this.checkedListBoxOptions.Items.AddRange(new object[] {
            "Explicit capture",
            "Ignore case",
            "Ignore whitespace",
            "Multiline",
            "Singleline",
            "Right to left"});
            this.checkedListBoxOptions.Location = new System.Drawing.Point(12, 67);
            this.checkedListBoxOptions.MultiColumn = true;
            this.checkedListBoxOptions.Name = "checkedListBoxOptions";
            this.checkedListBoxOptions.Size = new System.Drawing.Size(1164, 27);
            this.checkedListBoxOptions.TabIndex = 32;
            // 
            // checkBoxTreatAsSingleString
            // 
            this.checkBoxTreatAsSingleString.AutoSize = true;
            this.checkBoxTreatAsSingleString.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.checkBoxTreatAsSingleString.Location = new System.Drawing.Point(203, 494);
            this.checkBoxTreatAsSingleString.Name = "checkBoxTreatAsSingleString";
            this.checkBoxTreatAsSingleString.Size = new System.Drawing.Size(240, 30);
            this.checkBoxTreatAsSingleString.TabIndex = 33;
            this.checkBoxTreatAsSingleString.Text = "Treat as single string";
            this.checkBoxTreatAsSingleString.UseVisualStyleBackColor = true;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.label1.Location = new System.Drawing.Point(12, 112);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(202, 26);
            this.label1.TabIndex = 34;
            this.label1.Text = "Regular Expression";
            // 
            // label5
            // 
            this.label5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(726, 112);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(139, 26);
            this.label5.TabIndex = 28;
            this.label5.Text = "Interpretation";
            // 
            // MainForm
            // 
            this.AllowDrop = true;
            this.AutoScaleDimensions = new System.Drawing.SizeF(13F, 26F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1188, 748);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.checkedListBoxOptions);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.textBoxRegex);
            this.Controls.Add(this.labelLibrary);
            this.Controls.Add(this.treeView1);
            this.Controls.Add(this.textBoxReplacement);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.textBoxInterpretation);
            this.Controls.Add(this.toolStrip1);
            this.Controls.Add(this.textBoxInput);
            this.Controls.Add(this.checkBoxTreatAsSingleString);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MinimumSize = new System.Drawing.Size(1000, 500);
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Regular Expression Scratchpad 3.1";
            this.Load += new System.EventHandler(this.MainForm_Load);
            this.ResizeEnd += new System.EventHandler(this.MainForm_ResizeEnd);
            this.toolStrip1.ResumeLayout(false);
            this.toolStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.ToolStrip toolStrip1;
        private System.Windows.Forms.ToolStripButton toolStripButtonReplace;
        private System.Windows.Forms.ToolStripDropDownButton toolStripButtonInsert;
        private System.Windows.Forms.RichTextBox textBoxInput;
        private System.Windows.Forms.RichTextBox textBoxInterpretation;
        private System.Windows.Forms.RichTextBox textBoxReplacement;
        private System.Windows.Forms.ToolStripMenuItem anchorsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem beginningOfStringToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem beginningOfMultilineAToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem endOfStringToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem endOfMultilineZToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem wordBoundrybToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem nonwordBoundryBToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem conditionalsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem expressionexpyesnoToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem namedToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem characterClassesToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem groupcharsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem negatedGroupcharsToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem anyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem wordazAZ09wToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem nonwordWToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem whitespacefnrvsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem nonwhitespaceSToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem decimalDigitdToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem nondecimalDigitDToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem characterShortcutsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem carriageReturnrToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem bellaToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem cTRLCharCletterToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem unicodeCharuxxxToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aSCIIValuexnnToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem tabtToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem verticalTabZvToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem newlinnToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem escToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem formFeedfToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem groupingToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem captureexpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem namedCapturenamexToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem noncpatureToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem alternationxyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem optionsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ignoreCaseiToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ignoreCaseOffiToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ignoreWhitespacexToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem ignoreWhitespaceOffxToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem explicitCapturenToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem explicitCaptureOffnToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem multilinemToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem multilineOffmToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem singlelinesToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem singlelineOffsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem quantifiersToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem atLeastNnToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exactlyNnToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem oneOrMoreToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fromNToMnmToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem zeroOrMoreToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem zeroOrOneToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripMenuItem2;
        private System.Windows.Forms.ToolStripMenuItem atLeastNNongreedynToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exacltyNNongreedynToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem oneOrMoreNonGreedyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fromNToMNonGreedynmToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem zeroOrMoreNonGreedyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem zeroOrOneNonGreedyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem zerowidthToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem negativeLookaheadxToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem negativeLookbehindxToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem positiveLookaheadxToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem positiveLookbehindToolStripMenuItem;
        private System.Windows.Forms.ToolStripButton toolStripButton2;
        private System.Windows.Forms.ToolStripButton toolStripButtonLibrary;
        private System.Windows.Forms.TreeView treeView1;
        private System.Windows.Forms.Label labelLibrary;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.RichTextBox textBoxRegex;
        private System.Windows.Forms.ToolStripButton toolStripDropDownButton1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator4;
        private System.Windows.Forms.ToolTip toolTip1;
        private System.Windows.Forms.ToolStripButton toolStripButtonReplaceInFiles;
        private System.Windows.Forms.FolderBrowserDialog folderBrowserDialog1;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.ToolStripButton toolStripButton1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator3;
        private System.Windows.Forms.ToolStripButton toolStripMatch;
        private System.Windows.Forms.CheckedListBox checkedListBoxOptions;
        private System.Windows.Forms.CheckBox checkBoxTreatAsSingleString;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label5;
    }
}

