//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by VS
// </autogenerated>
//------------------------------------------------------------------------------
namespace RegularExpressionScratchpad
{
    public partial class RegExLibrary
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RegExLibrary));
            this.listBoxActions = new System.Windows.Forms.ListBox();
            this.contextMenuStripActions = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.newActionToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.deleteToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
            this.textBoxPattern = new System.Windows.Forms.TextBox();
            this.textBoxReplacement = new System.Windows.Forms.TextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.checkBoxRecursion = new System.Windows.Forms.CheckBox();
            this.buttonSave = new System.Windows.Forms.Button();
            this.contextMenuStripLibrary = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.addNewGroupToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.addNewTaskToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.deleteToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.groupBoxActions = new System.Windows.Forms.GroupBox();
            this.toolTip1 = new System.Windows.Forms.ToolTip(this.components);
            this.listBoxLibraryGroups = new System.Windows.Forms.ListBox();
            this.contextMenuStripActions.SuspendLayout();
            this.contextMenuStripLibrary.SuspendLayout();
            this.groupBoxActions.SuspendLayout();
            this.SuspendLayout();
            // 
            // listBoxActions
            // 
            this.listBoxActions.ContextMenuStrip = this.contextMenuStripActions;
            this.listBoxActions.FormattingEnabled = true;
            this.listBoxActions.Location = new System.Drawing.Point(6, 16);
            this.listBoxActions.Name = "listBoxActions";
            this.listBoxActions.Size = new System.Drawing.Size(120, 225);
            this.listBoxActions.TabIndex = 2;
            this.toolTip1.SetToolTip(this.listBoxActions, "Right-click for options");
            this.listBoxActions.SelectedIndexChanged += new System.EventHandler(this.listBoxActions_SelectedIndexChanged);
            // 
            // contextMenuStripActions
            // 
            this.contextMenuStripActions.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.newActionToolStripMenuItem,
            this.deleteToolStripMenuItem1});
            this.contextMenuStripActions.Name = "contextMenuStripActions";
            this.contextMenuStripActions.Size = new System.Drawing.Size(140, 48);
            // 
            // newActionToolStripMenuItem
            // 
            this.newActionToolStripMenuItem.Name = "newActionToolStripMenuItem";
            this.newActionToolStripMenuItem.Size = new System.Drawing.Size(139, 22);
            this.newActionToolStripMenuItem.Text = "New &Action";
            // 
            // deleteToolStripMenuItem1
            // 
            this.deleteToolStripMenuItem1.Name = "deleteToolStripMenuItem1";
            this.deleteToolStripMenuItem1.Size = new System.Drawing.Size(139, 22);
            this.deleteToolStripMenuItem1.Text = "&Delete";
            // 
            // textBoxPattern
            // 
            this.textBoxPattern.Location = new System.Drawing.Point(135, 32);
            this.textBoxPattern.Name = "textBoxPattern";
            this.textBoxPattern.Size = new System.Drawing.Size(357, 20);
            this.textBoxPattern.TabIndex = 3;
            // 
            // textBoxReplacement
            // 
            this.textBoxReplacement.Location = new System.Drawing.Point(135, 80);
            this.textBoxReplacement.Name = "textBoxReplacement";
            this.textBoxReplacement.Size = new System.Drawing.Size(357, 20);
            this.textBoxReplacement.TabIndex = 4;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(132, 64);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(94, 13);
            this.label4.TabIndex = 8;
            this.label4.Text = "Replacement Text";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(132, 16);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(86, 13);
            this.label5.TabIndex = 9;
            this.label5.Text = "Pattern to Match";
            // 
            // checkBoxRecursion
            // 
            this.checkBoxRecursion.AutoSize = true;
            this.checkBoxRecursion.Location = new System.Drawing.Point(135, 106);
            this.checkBoxRecursion.Name = "checkBoxRecursion";
            this.checkBoxRecursion.Size = new System.Drawing.Size(119, 17);
            this.checkBoxRecursion.TabIndex = 10;
            this.checkBoxRecursion.Text = "Supports Recursion";
            this.checkBoxRecursion.UseVisualStyleBackColor = true;
            // 
            // buttonSave
            // 
            this.buttonSave.Location = new System.Drawing.Point(630, 263);
            this.buttonSave.Name = "buttonSave";
            this.buttonSave.Size = new System.Drawing.Size(75, 23);
            this.buttonSave.TabIndex = 11;
            this.buttonSave.Text = "Save";
            this.buttonSave.UseVisualStyleBackColor = true;
            this.buttonSave.Click += new System.EventHandler(this.buttonSave_Click);
            // 
            // contextMenuStripLibrary
            // 
            this.contextMenuStripLibrary.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.addNewGroupToolStripMenuItem,
            this.addNewTaskToolStripMenuItem,
            this.deleteToolStripMenuItem});
            this.contextMenuStripLibrary.Name = "contextMenuStripLibrary";
            this.contextMenuStripLibrary.Size = new System.Drawing.Size(139, 70);
            // 
            // addNewGroupToolStripMenuItem
            // 
            this.addNewGroupToolStripMenuItem.Name = "addNewGroupToolStripMenuItem";
            this.addNewGroupToolStripMenuItem.Size = new System.Drawing.Size(138, 22);
            this.addNewGroupToolStripMenuItem.Text = "New &Group";
            // 
            // addNewTaskToolStripMenuItem
            // 
            this.addNewTaskToolStripMenuItem.Name = "addNewTaskToolStripMenuItem";
            this.addNewTaskToolStripMenuItem.Size = new System.Drawing.Size(138, 22);
            this.addNewTaskToolStripMenuItem.Text = "New &Task";
            // 
            // deleteToolStripMenuItem
            // 
            this.deleteToolStripMenuItem.Name = "deleteToolStripMenuItem";
            this.deleteToolStripMenuItem.Size = new System.Drawing.Size(138, 22);
            this.deleteToolStripMenuItem.Text = "&Delete";
            // 
            // groupBoxActions
            // 
            this.groupBoxActions.Controls.Add(this.checkBoxRecursion);
            this.groupBoxActions.Controls.Add(this.listBoxActions);
            this.groupBoxActions.Controls.Add(this.textBoxPattern);
            this.groupBoxActions.Controls.Add(this.textBoxReplacement);
            this.groupBoxActions.Controls.Add(this.label5);
            this.groupBoxActions.Controls.Add(this.label4);
            this.groupBoxActions.Location = new System.Drawing.Point(207, 3);
            this.groupBoxActions.Name = "groupBoxActions";
            this.groupBoxActions.Size = new System.Drawing.Size(498, 254);
            this.groupBoxActions.TabIndex = 14;
            this.groupBoxActions.TabStop = false;
            this.groupBoxActions.Text = "Task Actions and Details";
            // 
            // listBoxLibraryGroups
            // 
            this.listBoxLibraryGroups.ContextMenuStrip = this.contextMenuStripActions;
            this.listBoxLibraryGroups.Dock = System.Windows.Forms.DockStyle.Left;
            this.listBoxLibraryGroups.FormattingEnabled = true;
            this.listBoxLibraryGroups.Location = new System.Drawing.Point(0, 0);
            this.listBoxLibraryGroups.Name = "listBoxLibraryGroups";
            this.listBoxLibraryGroups.Size = new System.Drawing.Size(199, 290);
            this.listBoxLibraryGroups.TabIndex = 15;
            this.toolTip1.SetToolTip(this.listBoxLibraryGroups, "Right-click for options");
            this.listBoxLibraryGroups.SelectedIndexChanged += new System.EventHandler(this.listBoxLibraryGroups_SelectedIndexChanged);
            // 
            // RegExLibrary
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(717, 292);
            this.Controls.Add(this.listBoxLibraryGroups);
            this.Controls.Add(this.groupBoxActions);
            this.Controls.Add(this.buttonSave);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "RegExLibrary";
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Regular Expression Library";
            this.Load += new System.EventHandler(this.RegExLibrary_Load);
            this.contextMenuStripActions.ResumeLayout(false);
            this.contextMenuStripLibrary.ResumeLayout(false);
            this.groupBoxActions.ResumeLayout(false);
            this.groupBoxActions.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ListBox listBoxActions;
        private System.Windows.Forms.TextBox textBoxPattern;
        private System.Windows.Forms.TextBox textBoxReplacement;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.CheckBox checkBoxRecursion;
        private System.Windows.Forms.Button buttonSave;
        private System.Windows.Forms.ContextMenuStrip contextMenuStripLibrary;
        private System.Windows.Forms.GroupBox groupBoxActions;
        private System.Windows.Forms.ContextMenuStrip contextMenuStripActions;
        private System.Windows.Forms.ToolStripMenuItem newActionToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem deleteToolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem addNewGroupToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem addNewTaskToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem deleteToolStripMenuItem;
        private System.Windows.Forms.ToolTip toolTip1;
        private System.Windows.Forms.ListBox listBoxLibraryGroups;


    }
}